# """add claim history

# Revision ID: 31abd1a6ab4c
# Revises: 44e3f6503593
# Create Date: 2026-09-26 11:49:12.843593
# """
# from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# revision = '31abd1a6ab4c'
# down_revision = '44e3f6503593'
# branch_labels = None
# depends_on = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('claim_history',
#     sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
#     sa.Column('claim_id', sa.String(length=20), nullable=False),
#     sa.Column('action', sa.String(length=50), nullable=False),
#     sa.Column('old_status', sa.String(length=30), nullable=True),
#     sa.Column('new_status', sa.String(length=30), nullable=False),
#     sa.Column('note', sa.Text(), nullable=True),
#     sa.Column('actor_type', sa.String(length=30), nullable=False),
#     sa.Column('actor_id', sa.String(length=50), nullable=True),
#     sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
#     sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('history_id')
#     )
#     op.create_index(op.f('ix_claim_history_claim_id'), 'claim_history', ['claim_id'], unique=False)
#     op.drop_constraint(op.f('fk_claim_analysis_claim'), 'claim_analyses', type_='foreignkey')
#     op.alter_column('claims', 'customer_id',
#                existing_type=sa.VARCHAR(length=20),
#                type_=sa.String(length=50),
#                existing_nullable=False)
#     op.alter_column('claims', 'policy_id',
#                existing_type=sa.VARCHAR(length=20),
#                type_=sa.String(length=50),
#                existing_nullable=False)
#     op.alter_column('claims', 'incident_type',
#                existing_type=sa.VARCHAR(length=50),
#                nullable=False)
#     op.alter_column('claims', 'incident_location',
#                existing_type=sa.TEXT(),
#                type_=sa.String(),
#                nullable=False)
#     op.alter_column('claims', 'number_of_vehicles_involved',
#                existing_type=sa.INTEGER(),
#                nullable=False)
#     op.alter_column('claims', 'bodily_injuries',
#                existing_type=sa.INTEGER(),
#                nullable=False)
#     op.alter_column('claims', 'witnesses',
#                existing_type=sa.INTEGER(),
#                nullable=False)
#     op.alter_column('claims', 'total_claim_amount',
#                existing_type=sa.NUMERIC(precision=12, scale=2),
#                nullable=False)
#     op.alter_column('claims', 'claim_description',
#                existing_type=sa.TEXT(),
#                nullable=False)
#     op.alter_column('claims', 'status',
#                existing_type=sa.VARCHAR(length=30),
#                nullable=False,
#                existing_server_default=sa.text("'submitted'::character varying"))
#     op.alter_column('claims', 'created_at',
#                existing_type=postgresql.TIMESTAMP(),
#                nullable=False,
#                existing_server_default=sa.text('CURRENT_TIMESTAMP'))
#     op.create_index(op.f('ix_claims_customer_id'), 'claims', ['customer_id'], unique=False)
#     op.create_index(op.f('ix_claims_policy_id'), 'claims', ['policy_id'], unique=False)
#     op.alter_column('customers', 'customer_id',
#                existing_type=sa.VARCHAR(length=20),
#                type_=sa.String(length=50),
#                existing_nullable=False)
#     op.alter_column('customers', 'date_of_birth',
#                existing_type=sa.DATE(),
#                nullable=False)
#     op.alter_column('customers', 'sex',
#                existing_type=sa.VARCHAR(length=20),
#                nullable=False)
#     op.alter_column('customers', 'education_level',
#                existing_type=sa.VARCHAR(length=50),
#                nullable=False)
#     op.alter_column('customers', 'occupation',
#                existing_type=sa.VARCHAR(length=100),
#                nullable=False)
#     op.alter_column('customers', 'hobbies',
#                existing_type=sa.VARCHAR(length=100),
#                nullable=False)
#     op.alter_column('customers', 'relationship',
#                existing_type=sa.VARCHAR(length=50),
#                nullable=False)
#     op.alter_column('customers', 'zip_code',
#                existing_type=sa.VARCHAR(length=10),
#                nullable=False)
#     op.alter_column('policies', 'policy_id',
#                existing_type=sa.VARCHAR(length=20),
#                type_=sa.String(length=50),
#                existing_nullable=False)
#     op.alter_column('policies', 'customer_id',
#                existing_type=sa.VARCHAR(length=20),
#                type_=sa.String(length=50),
#                existing_nullable=False)
#     op.alter_column('policies', 'policy_bind_date',
#                existing_type=sa.DATE(),
#                nullable=False)
#     op.alter_column('policies', 'policy_state',
#                existing_type=sa.VARCHAR(length=10),
#                nullable=False)
#     op.alter_column('policies', 'policy_csl',
#                existing_type=sa.VARCHAR(length=20),
#                nullable=False)
#     op.alter_column('policies', 'deductible',
#                existing_type=sa.NUMERIC(precision=12, scale=2),
#                nullable=False)
#     op.alter_column('policies', 'annual_premium',
#                existing_type=sa.NUMERIC(precision=12, scale=2),
#                nullable=False)
#     op.alter_column('policies', 'umbrella_limit',
#                existing_type=sa.NUMERIC(precision=12, scale=2),
#                nullable=False)
#     op.alter_column('policies', 'policy_status',
#                existing_type=sa.VARCHAR(length=20),
#                nullable=False,
#                existing_server_default=sa.text("'active'::character varying"))
#     op.drop_constraint(op.f('policies_policy_number_key'), 'policies', type_='unique')
#     op.create_index(op.f('ix_policies_customer_id'), 'policies', ['customer_id'], unique=False)
#     op.alter_column('previous_claims', 'previous_claim_id',
#                existing_type=sa.VARCHAR(length=20),
#                type_=sa.Integer(),
#                existing_nullable=False,
#                autoincrement=True)
#     op.alter_column('previous_claims', 'customer_id',
#                existing_type=sa.VARCHAR(length=20),
#                type_=sa.String(length=50),
#                existing_nullable=False)
#     op.alter_column('previous_claims', 'policy_id',
#                existing_type=sa.VARCHAR(length=20),
#                type_=sa.String(length=50),
#                existing_nullable=False)
#     op.alter_column('previous_claims', 'claim_amount',
#                existing_type=sa.NUMERIC(precision=12, scale=2),
#                nullable=False)
#     op.alter_column('previous_claims', 'incident_type',
#                existing_type=sa.VARCHAR(length=50),
#                nullable=False)
#     op.alter_column('previous_claims', 'incident_severity',
#                existing_type=sa.VARCHAR(length=50),
#                nullable=False)
#     op.create_index(op.f('ix_previous_claims_customer_id'), 'previous_claims', ['customer_id'], unique=False)
#     op.create_index(op.f('ix_previous_claims_policy_id'), 'previous_claims', ['policy_id'], unique=False)
#     op.alter_column('vehicles', 'vehicle_id',
#                existing_type=sa.VARCHAR(length=20),
#                type_=sa.Integer(),
#                existing_nullable=False,
#                autoincrement=True)
#     op.alter_column('vehicles', 'customer_id',
#                existing_type=sa.VARCHAR(length=20),
#                type_=sa.String(length=50),
#                existing_nullable=False)
#     op.alter_column('vehicles', 'policy_id',
#                existing_type=sa.VARCHAR(length=20),
#                type_=sa.String(length=50),
#                existing_nullable=False)
#     op.alter_column('vehicles', 'make',
#                existing_type=sa.VARCHAR(length=50),
#                nullable=False)
#     op.alter_column('vehicles', 'model',
#                existing_type=sa.VARCHAR(length=100),
#                nullable=False)
#     op.alter_column('vehicles', 'year',
#                existing_type=sa.INTEGER(),
#                nullable=False)
#     op.create_index(op.f('ix_vehicles_customer_id'), 'vehicles', ['customer_id'], unique=False)
#     op.create_index(op.f('ix_vehicles_policy_id'), 'vehicles', ['policy_id'], unique=False)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_vehicles_policy_id'), table_name='vehicles')
#     op.drop_index(op.f('ix_vehicles_customer_id'), table_name='vehicles')
#     op.alter_column('vehicles', 'year',
#                existing_type=sa.INTEGER(),
#                nullable=True)
#     op.alter_column('vehicles', 'model',
#                existing_type=sa.VARCHAR(length=100),
#                nullable=True)
#     op.alter_column('vehicles', 'make',
#                existing_type=sa.VARCHAR(length=50),
#                nullable=True)
#     op.alter_column('vehicles', 'policy_id',
#                existing_type=sa.String(length=50),
#                type_=sa.VARCHAR(length=20),
#                existing_nullable=False)
#     op.alter_column('vehicles', 'customer_id',
#                existing_type=sa.String(length=50),
#                type_=sa.VARCHAR(length=20),
#                existing_nullable=False)
#     op.alter_column('vehicles', 'vehicle_id',
#                existing_type=sa.Integer(),
#                type_=sa.VARCHAR(length=20),
#                existing_nullable=False,
#                autoincrement=True)
#     op.drop_index(op.f('ix_previous_claims_policy_id'), table_name='previous_claims')
#     op.drop_index(op.f('ix_previous_claims_customer_id'), table_name='previous_claims')
#     op.alter_column('previous_claims', 'incident_severity',
#                existing_type=sa.VARCHAR(length=50),
#                nullable=True)
#     op.alter_column('previous_claims', 'incident_type',
#                existing_type=sa.VARCHAR(length=50),
#                nullable=True)
#     op.alter_column('previous_claims', 'claim_amount',
#                existing_type=sa.NUMERIC(precision=12, scale=2),
#                nullable=True)
#     op.alter_column('previous_claims', 'policy_id',
#                existing_type=sa.String(length=50),
#                type_=sa.VARCHAR(length=20),
#                existing_nullable=False)
#     op.alter_column('previous_claims', 'customer_id',
#                existing_type=sa.String(length=50),
#                type_=sa.VARCHAR(length=20),
#                existing_nullable=False)
#     op.alter_column('previous_claims', 'previous_claim_id',
#                existing_type=sa.Integer(),
#                type_=sa.VARCHAR(length=20),
#                existing_nullable=False,
#                autoincrement=True)
#     op.drop_index(op.f('ix_policies_customer_id'), table_name='policies')
#     op.create_unique_constraint(op.f('policies_policy_number_key'), 'policies', ['policy_number'], postgresql_nulls_not_distinct=False)
#     op.alter_column('policies', 'policy_status',
#                existing_type=sa.VARCHAR(length=20),
#                nullable=True,
#                existing_server_default=sa.text("'active'::character varying"))
#     op.alter_column('policies', 'umbrella_limit',
#                existing_type=sa.NUMERIC(precision=12, scale=2),
#                nullable=True)
#     op.alter_column('policies', 'annual_premium',
#                existing_type=sa.NUMERIC(precision=12, scale=2),
#                nullable=True)
#     op.alter_column('policies', 'deductible',
#                existing_type=sa.NUMERIC(precision=12, scale=2),
#                nullable=True)
#     op.alter_column('policies', 'policy_csl',
#                existing_type=sa.VARCHAR(length=20),
#                nullable=True)
#     op.alter_column('policies', 'policy_state',
#                existing_type=sa.VARCHAR(length=10),
#                nullable=True)
#     op.alter_column('policies', 'policy_bind_date',
#                existing_type=sa.DATE(),
#                nullable=True)
#     op.alter_column('policies', 'customer_id',
#                existing_type=sa.String(length=50),
#                type_=sa.VARCHAR(length=20),
#                existing_nullable=False)
#     op.alter_column('policies', 'policy_id',
#                existing_type=sa.String(length=50),
#                type_=sa.VARCHAR(length=20),
#                existing_nullable=False)
#     op.alter_column('customers', 'zip_code',
#                existing_type=sa.VARCHAR(length=10),
#                nullable=True)
#     op.alter_column('customers', 'relationship',
#                existing_type=sa.VARCHAR(length=50),
#                nullable=True)
#     op.alter_column('customers', 'hobbies',
#                existing_type=sa.VARCHAR(length=100),
#                nullable=True)
#     op.alter_column('customers', 'occupation',
#                existing_type=sa.VARCHAR(length=100),
#                nullable=True)
#     op.alter_column('customers', 'education_level',
#                existing_type=sa.VARCHAR(length=50),
#                nullable=True)
#     op.alter_column('customers', 'sex',
#                existing_type=sa.VARCHAR(length=20),
#                nullable=True)
#     op.alter_column('customers', 'date_of_birth',
#                existing_type=sa.DATE(),
#                nullable=True)
#     op.alter_column('customers', 'customer_id',
#                existing_type=sa.String(length=50),
#                type_=sa.VARCHAR(length=20),
#                existing_nullable=False)
#     op.drop_index(op.f('ix_claims_policy_id'), table_name='claims')
#     op.drop_index(op.f('ix_claims_customer_id'), table_name='claims')
#     op.alter_column('claims', 'created_at',
#                existing_type=postgresql.TIMESTAMP(),
#                nullable=True,
#                existing_server_default=sa.text('CURRENT_TIMESTAMP'))
#     op.alter_column('claims', 'status',
#                existing_type=sa.VARCHAR(length=30),
#                nullable=True,
#                existing_server_default=sa.text("'submitted'::character varying"))
#     op.alter_column('claims', 'claim_description',
#                existing_type=sa.TEXT(),
#                nullable=True)
#     op.alter_column('claims', 'total_claim_amount',
#                existing_type=sa.NUMERIC(precision=12, scale=2),
#                nullable=True)
#     op.alter_column('claims', 'witnesses',
#                existing_type=sa.INTEGER(),
#                nullable=True)
#     op.alter_column('claims', 'bodily_injuries',
#                existing_type=sa.INTEGER(),
#                nullable=True)
#     op.alter_column('claims', 'number_of_vehicles_involved',
#                existing_type=sa.INTEGER(),
#                nullable=True)
#     op.alter_column('claims', 'incident_location',
#                existing_type=sa.String(),
#                type_=sa.TEXT(),
#                nullable=True)
#     op.alter_column('claims', 'incident_type',
#                existing_type=sa.VARCHAR(length=50),
#                nullable=True)
#     op.alter_column('claims', 'policy_id',
#                existing_type=sa.String(length=50),
#                type_=sa.VARCHAR(length=20),
#                existing_nullable=False)
#     op.alter_column('claims', 'customer_id',
#                existing_type=sa.String(length=50),
#                type_=sa.VARCHAR(length=20),
#                existing_nullable=False)
#     op.create_foreign_key(op.f('fk_claim_analysis_claim'), 'claim_analyses', 'claims', ['claim_id'], ['claim_id'], ondelete='CASCADE')
#     op.drop_index(op.f('ix_claim_history_claim_id'), table_name='claim_history')
#     op.drop_table('claim_history')
#     # ### end Alembic commands ###






"""add claim history

Revision ID: 31abd1a6ab4c
Revises: 44e3f6503593
"""

from alembic import op
import sqlalchemy as sa


revision = "31abd1a6ab4c"
down_revision = "44e3f6503593"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "claim_history",
        sa.Column(
            "history_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "claim_id",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "old_status",
            sa.String(length=30),
            nullable=True,
        ),
        sa.Column(
            "new_status",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "note",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "actor_type",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "actor_id",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.claim_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("history_id"),
    )

    op.create_index(
        "ix_claim_history_claim_id",
        "claim_history",
        ["claim_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_claim_history_claim_id",
        table_name="claim_history",
    )
    op.drop_table("claim_history")
